BEGIN;
CREATE INDEX IF NOT EXISTS idx_run_log_job_ts ON run_log(job_name, timestamp);
CREATE INDEX IF NOT EXISTS idx_cfg_bond_index_list_code ON cfg_bond_index_list(index_code);
CREATE INDEX IF NOT EXISTS idx_raw_bond_curve_date ON raw_bond_curve(date);
CREATE INDEX IF NOT EXISTS idx_raw_bond_curve_curve_date ON raw_bond_curve(curve, date);
CREATE INDEX IF NOT EXISTS idx_raw_chinabond_bond_index_trade_date ON raw_chinabond_bond_index(trade_date);
CREATE INDEX IF NOT EXISTS idx_raw_chinabond_bond_index_code_date ON raw_chinabond_bond_index(index_code, trade_date);
CREATE INDEX IF NOT EXISTS idx_raw_chinabond_bond_index_type ON raw_chinabond_bond_index(type_lv1, type_lv2, type_lv3);
CREATE UNIQUE INDEX IF NOT EXISTS uidx_raw_chinabond_bond_index_trade_date_code_not_null ON raw_chinabond_bond_index(trade_date, index_code) WHERE index_code IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_raw_csindex_bond_index_trade_date ON raw_csindex_bond_index(trade_date);
CREATE INDEX IF NOT EXISTS idx_raw_csindex_bond_index_code_date ON raw_csindex_bond_index(index_code, trade_date);
CREATE INDEX IF NOT EXISTS idx_raw_csindex_bond_index_type ON raw_csindex_bond_index(type_lv1, type_lv2, type_lv3);
CREATE UNIQUE INDEX IF NOT EXISTS uidx_raw_csindex_bond_index_trade_date_code_not_null ON raw_csindex_bond_index(trade_date, index_code) WHERE index_code IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_raw_cnindex_bond_index_trade_date ON raw_cnindex_bond_index(trade_date);
CREATE INDEX IF NOT EXISTS idx_raw_cnindex_bond_index_code_date ON raw_cnindex_bond_index(index_code, trade_date);
CREATE INDEX IF NOT EXISTS idx_raw_cnindex_bond_index_type ON raw_cnindex_bond_index(type_lv1, type_lv2, type_lv3);
CREATE UNIQUE INDEX IF NOT EXISTS uidx_raw_cnindex_bond_index_trade_date_code_not_null ON raw_cnindex_bond_index(trade_date, index_code) WHERE index_code IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_raw_policy_rate_date ON raw_policy_rate(date);
CREATE INDEX IF NOT EXISTS idx_raw_policy_rate_type_term_date ON raw_policy_rate(type, term, date);
CREATE INDEX IF NOT EXISTS idx_raw_money_market_date ON raw_money_market(date);
CREATE INDEX IF NOT EXISTS idx_raw_futures_date ON raw_futures(date);
CREATE INDEX IF NOT EXISTS idx_raw_fred_date ON raw_fred(date);
CREATE INDEX IF NOT EXISTS idx_raw_alpha_vantage_date ON raw_alpha_vantage(date);
CREATE INDEX IF NOT EXISTS idx_raw_life_asset_date ON raw_life_asset(date);
CREATE INDEX IF NOT EXISTS idx_raw_jisilu_etf_snapshot_date ON raw_jisilu_etf(snapshot_date);
CREATE INDEX IF NOT EXISTS idx_raw_jisilu_etf_fund_date ON raw_jisilu_etf(fund_id, snapshot_date);
CREATE INDEX IF NOT EXISTS idx_raw_jisilu_etf_index_nm ON raw_jisilu_etf(index_nm);
CREATE INDEX IF NOT EXISTS idx_raw_jisilu_qdii_snapshot_date ON raw_jisilu_qdii(snapshot_date);
CREATE INDEX IF NOT EXISTS idx_raw_jisilu_qdii_market_date ON raw_jisilu_qdii(market, snapshot_date);
CREATE INDEX IF NOT EXISTS idx_raw_jisilu_qdii_fund_date ON raw_jisilu_qdii(fund_id, snapshot_date);
CREATE INDEX IF NOT EXISTS idx_raw_jisilu_qdii_index_nm ON raw_jisilu_qdii(index_nm);
CREATE INDEX IF NOT EXISTS idx_raw_jisilu_qdii_money_cd ON raw_jisilu_qdii(money_cd);
CREATE INDEX IF NOT EXISTS idx_raw_jisilu_treasury_snapshot_date ON raw_jisilu_treasury(snapshot_date);
CREATE INDEX IF NOT EXISTS idx_raw_jisilu_treasury_ytm ON raw_jisilu_treasury(ytm, snapshot_date);
CREATE INDEX IF NOT EXISTS idx_raw_jisilu_treasury_volume ON raw_jisilu_treasury(volume_wan, snapshot_date);
CREATE INDEX IF NOT EXISTS idx_raw_sse_lively_bond_trade_date ON raw_sse_lively_bond(trade_date);
CREATE INDEX IF NOT EXISTS idx_raw_sse_lively_bond_bond_date ON raw_sse_lively_bond(bond_id, trade_date);
CREATE INDEX IF NOT EXISTS idx_raw_sse_lively_bond_amount ON raw_sse_lively_bond(amount_wanyuan, trade_date);
CREATE INDEX IF NOT EXISTS idx_metrics_metric_key ON metrics(metric_key, date);
CREATE INDEX IF NOT EXISTS idx_signal_main_key ON signal_main(signal_key, date);
COMMIT;
