/********************
 * 30_metric_catalog.js
 * 指标目录：纯数据版
 * 仅维护指标元数据，不放业务逻辑。
 ********************/

var METRIC_CATALOG_ = [
  {
    code: "gov_1y",
    zh: "1年期国债到期收益率",
    en: "1Y China Government Bond yield",
    category: "利率水平",
    storage_unit: "decimal",
    display_unit: "percent",
    importance: "核心",
    rise: "通常意味着短端利率中枢上行、货币环境边际收紧或短端供给扰动。",
    fall: "通常意味着短端利率中枢下行、流动性改善或宽松预期升温。",
    usage: "观察无风险利率短端水平与政策传导。",
    note: "",
    aliases: []
  },
  {
    code: "gov_2y",
    zh: "2年期国债到期收益率",
    en: "2Y China Government Bond yield",
    category: "利率水平",
    storage_unit: "decimal",
    display_unit: "percent",
    importance: "重要",
    rise: "通常意味着短中端利率抬升。",
    fall: "通常意味着短中端利率回落。",
    usage: "观察国债曲线短端定价。",
    note: "",
    aliases: []
  },
  {
    code: "gov_3y",
    zh: "3年期国债到期收益率",
    en: "3Y China Government Bond yield",
    category: "利率水平",
    storage_unit: "decimal",
    display_unit: "percent",
    importance: "重要",
    rise: "通常意味着中短端利率上行。",
    fall: "通常意味着中短端利率回落。",
    usage: "观察中短端定价与政策预期。",
    note: "",
    aliases: []
  },
  {
    code: "gov_5y",
    zh: "5年期国债到期收益率",
    en: "5Y China Government Bond yield",
    category: "利率水平",
    storage_unit: "decimal",
    display_unit: "percent",
    importance: "核心",
    rise: "通常意味着中端利率上行、增长/通胀预期走强或供给压力上升。",
    fall: "通常意味着中端利率下行、宽松预期增强或避险需求升温。",
    usage: "观察国债中端基准收益率。",
    note: "",
    aliases: []
  },
  {
    code: "gov_10y",
    zh: "10年期国债到期收益率",
    en: "10Y China Government Bond yield",
    category: "利率水平",
    storage_unit: "decimal",
    display_unit: "percent",
    importance: "核心",
    rise: "通常意味着长端利率抬升，增长预期、供给压力或风险偏好改善。",
    fall: "通常意味着长端利率下行，避险需求增强或宽松预期升温。",
    usage: "核心锚点；用于久期、估值和宏观利率判断。",
    note: "",
    aliases: []
  },
  {
    code: "gov_30y",
    zh: "30年期国债到期收益率",
    en: "30Y China Government Bond yield",
    category: "利率水平",
    storage_unit: "decimal",
    display_unit: "percent",
    importance: "重要",
    rise: "通常意味着超长端利率抬升、久期风险承受下降。",
    fall: "通常意味着超长端利率回落、久期偏好提升。",
    usage: "观察超长端久期偏好。",
    note: "",
    aliases: []
  },
  {
    code: "cdb_3y",
    zh: "3年期国开债到期收益率",
    en: "3Y China Development Bank bond yield",
    category: "利率水平",
    storage_unit: "decimal",
    display_unit: "percent",
    importance: "重要",
    rise: "通常意味着政策性金融债中短端利率上行。",
    fall: "通常意味着政策性金融债中短端利率回落。",
    usage: "观察国开债中短端水平。",
    note: "",
    aliases: []
  },
  {
    code: "cdb_5y",
    zh: "5年期国开债到期收益率",
    en: "5Y China Development Bank bond yield",
    category: "利率水平",
    storage_unit: "decimal",
    display_unit: "percent",
    importance: "重要",
    rise: "通常意味着国开债中端利率上行。",
    fall: "通常意味着国开债中端利率回落。",
    usage: "观察国开债中端水平。",
    note: "",
    aliases: []
  },
  {
    code: "cdb_10y",
    zh: "10年期国开债到期收益率",
    en: "10Y China Development Bank bond yield",
    category: "利率水平",
    storage_unit: "decimal",
    display_unit: "percent",
    importance: "核心",
    rise: "通常意味着政策性金融债长端利率抬升。",
    fall: "通常意味着政策性金融债长端利率回落。",
    usage: "配合国债利差观察利率债相对价值。",
    note: "",
    aliases: []
  },
  {
    code: "aaa_credit_1y",
    zh: "1年期AAA信用债到期收益率",
    en: "1Y AAA credit bond yield",
    category: "信用利率",
    storage_unit: "decimal",
    display_unit: "percent",
    importance: "重要",
    rise: "通常意味着高等级信用短端融资成本抬升。",
    fall: "通常意味着高等级信用短端融资成本下降。",
    usage: "观察高等级信用短端定价。",
    note: "",
    aliases: []
  },
  {
    code: "aaa_credit_3y",
    zh: "3年期AAA信用债到期收益率",
    en: "3Y AAA credit bond yield",
    category: "信用利率",
    storage_unit: "decimal",
    display_unit: "percent",
    importance: "重要",
    rise: "通常意味着高等级信用中端收益率上行。",
    fall: "通常意味着高等级信用中端收益率回落。",
    usage: "观察高等级信用中端定价。",
    note: "",
    aliases: []
  },
  {
    code: "aaa_credit_5y",
    zh: "5年期AAA信用债到期收益率",
    en: "5Y AAA credit bond yield",
    category: "信用利率",
    storage_unit: "decimal",
    display_unit: "percent",
    importance: "核心",
    rise: "通常意味着高等级信用长端信用利差或无风险利率上行。",
    fall: "通常意味着高等级信用估值改善。",
    usage: "信用债主观察指标。",
    note: "",
    aliases: []
  },
  {
    code: "aa_plus_credit_1y",
    zh: "1年期AA+信用债到期收益率",
    en: "1Y AA+ credit bond yield",
    category: "信用利率",
    storage_unit: "decimal",
    display_unit: "percent",
    importance: "重要",
    rise: "通常意味着中高等级信用短端风险溢价上行。",
    fall: "通常意味着中高等级信用短端风险溢价回落。",
    usage: "观察下沉方向风险偏好。",
    note: "",
    aliases: []
  },
  {
    code: "aaa_plus_mtn_1y",
    zh: "1年期AAA+中票到期收益率",
    en: "1Y AAA+ medium-term note yield",
    category: "信用利率",
    storage_unit: "decimal",
    display_unit: "percent",
    importance: "观察",
    rise: "通常意味着高等级中票短端收益率上行。",
    fall: "通常意味着高等级中票短端收益率回落。",
    usage: "细分信用结构观察。",
    note: "",
    aliases: []
  },
  {
    code: "aaa_mtn_1y",
    zh: "1年期AAA中票到期收益率",
    en: "1Y AAA medium-term note yield",
    category: "信用利率",
    storage_unit: "decimal",
    display_unit: "percent",
    importance: "观察",
    rise: "通常意味着AAA中票短端收益率上行。",
    fall: "通常意味着AAA中票短端收益率回落。",
    usage: "观察中票短端。",
    note: "",
    aliases: []
  },
  {
    code: "aaa_mtn_3y",
    zh: "3年期AAA中票到期收益率",
    en: "3Y AAA medium-term note yield",
    category: "信用利率",
    storage_unit: "decimal",
    display_unit: "percent",
    importance: "观察",
    rise: "通常意味着AAA中票中端收益率上行。",
    fall: "通常意味着AAA中票中端收益率回落。",
    usage: "观察中票中端。",
    note: "",
    aliases: []
  },
  {
    code: "aaa_mtn_5y",
    zh: "5年期AAA中票到期收益率",
    en: "5Y AAA medium-term note yield",
    category: "信用利率",
    storage_unit: "decimal",
    display_unit: "percent",
    importance: "观察",
    rise: "通常意味着AAA中票长端收益率上行。",
    fall: "通常意味着AAA中票长端收益率回落。",
    usage: "观察中票长端。",
    note: "",
    aliases: []
  },
  {
    code: "aaa_ncd_1y",
    zh: "1年期AAA同业存单到期收益率",
    en: "1Y AAA negotiable certificate of deposit yield",
    category: "资金与存单",
    storage_unit: "decimal",
    display_unit: "percent",
    importance: "核心",
    rise: "通常意味着存单融资成本上行、银行负债端偏紧。",
    fall: "通常意味着存单融资成本下行、负债端改善。",
    usage: "观察银行负债成本与资金面传导。",
    note: "",
    aliases: []
  },
  {
    code: "aaa_bank_bond_1y",
    zh: "1年期AAA银行债到期收益率",
    en: "1Y AAA bank bond yield",
    category: "信用利率",
    storage_unit: "decimal",
    display_unit: "percent",
    importance: "观察",
    rise: "通常意味着银行债短端收益率上行。",
    fall: "通常意味着银行债短端收益率回落。",
    usage: "观察银行债估值。",
    note: "",
    aliases: []
  },
  {
    code: "aaa_bank_bond_3y",
    zh: "3年期AAA银行债到期收益率",
    en: "3Y AAA bank bond yield",
    category: "信用利率",
    storage_unit: "decimal",
    display_unit: "percent",
    importance: "观察",
    rise: "通常意味着银行债中端收益率上行。",
    fall: "通常意味着银行债中端收益率回落。",
    usage: "观察银行债估值。",
    note: "",
    aliases: []
  },
  {
    code: "aaa_bank_bond_5y",
    zh: "5年期AAA银行债到期收益率",
    en: "5Y AAA bank bond yield",
    category: "信用利率",
    storage_unit: "decimal",
    display_unit: "percent",
    importance: "观察",
    rise: "通常意味着银行债长端收益率上行。",
    fall: "通常意味着银行债长端收益率回落。",
    usage: "观察银行债估值。",
    note: "",
    aliases: []
  },
  {
    code: "aaa_lgfv_1y",
    zh: "1年期AAA城投债到期收益率",
    en: "1Y AAA LGFV bond yield",
    category: "信用利率",
    storage_unit: "decimal",
    display_unit: "percent",
    importance: "重要",
    rise: "通常意味着高等级城投短端融资成本抬升。",
    fall: "通常意味着高等级城投短端融资成本回落。",
    usage: "观察城投融资环境。",
    note: "",
    aliases: []
  },
  {
    code: "local_gov_5y",
    zh: "5年期地方债到期收益率",
    en: "5Y local government bond yield",
    category: "利率水平",
    storage_unit: "decimal",
    display_unit: "percent",
    importance: "重要",
    rise: "通常意味着地方债中端收益率上行。",
    fall: "通常意味着地方债中端收益率回落。",
    usage: "观察地方债估值与供给影响。",
    note: "",
    aliases: []
  },
  {
    code: "local_gov_10y",
    zh: "10年期地方债到期收益率",
    en: "10Y local government bond yield",
    category: "利率水平",
    storage_unit: "decimal",
    display_unit: "percent",
    importance: "重要",
    rise: "通常意味着地方债长端收益率上行。",
    fall: "通常意味着地方债长端收益率回落。",
    usage: "观察地方债长端估值。",
    note: "",
    aliases: []
  },
  {
    code: "dr007_weighted_rate",
    zh: "DR007加权利率",
    en: "DR007 weighted repo rate",
    category: "资金面",
    storage_unit: "decimal",
    display_unit: "percent",
    importance: "核心",
    rise: "通常意味着银行间资金偏紧。",
    fall: "通常意味着银行间资金偏松。",
    usage: "最核心的资金面日度指标之一。",
    note: "",
    aliases: []
  },
  {
    code: "omo_7d",
    zh: "7天逆回购利率",
    en: "7-day reverse repo rate",
    category: "政策利率",
    storage_unit: "decimal",
    display_unit: "percent",
    importance: "核心",
    rise: "通常意味着公开市场操作利率抬升。",
    fall: "通常意味着公开市场操作利率下调。",
    usage: "观察政策利率锚。",
    note: "",
    aliases: []
  },
  {
    code: "mlf_1y",
    zh: "1年期MLF利率",
    en: "1Y Medium-term Lending Facility rate",
    category: "政策利率",
    storage_unit: "decimal",
    display_unit: "percent",
    importance: "核心",
    rise: "通常意味着中期政策利率抬升。",
    fall: "通常意味着中期政策利率回落。",
    usage: "观察中期政策利率与银行负债定价。",
    note: "",
    aliases: []
  },
  {
    code: "lpr_1y",
    zh: "1年期LPR",
    en: "1Y Loan Prime Rate",
    category: "政策利率",
    storage_unit: "decimal",
    display_unit: "percent",
    importance: "核心",
    rise: "通常意味着贷款利率中枢上行。",
    fall: "通常意味着贷款利率中枢下行。",
    usage: "观察实体融资成本。",
    note: "",
    aliases: []
  },
  {
    code: "lpr_5y",
    zh: "5年期以上LPR",
    en: "5Y+ Loan Prime Rate",
    category: "政策利率",
    storage_unit: "decimal",
    display_unit: "percent",
    importance: "核心",
    rise: "通常意味着中长期贷款定价抬升。",
    fall: "通常意味着按揭与中长期贷款定价下行。",
    usage: "房地产与中长期融资的重要锚。",
    note: "",
    aliases: []
  },
  {
    code: "ust_2y",
    zh: "2年期美债收益率",
    en: "2Y U.S. Treasury yield",
    category: "海外利率",
    storage_unit: "decimal",
    display_unit: "percent",
    importance: "重要",
    rise: "通常意味着美联储短端政策预期更鹰。",
    fall: "通常意味着美联储短端政策预期转鸽。",
    usage: "观察全球短端利率与美元压力。",
    note: "",
    aliases: []
  },
  {
    code: "ust_10y",
    zh: "10年期美债收益率",
    en: "10Y U.S. Treasury yield",
    category: "海外利率",
    storage_unit: "decimal",
    display_unit: "percent",
    importance: "核心",
    rise: "通常意味着全球长端无风险利率抬升。",
    fall: "通常意味着全球长端无风险利率回落。",
    usage: "观察中美利差与全球定价锚。",
    note: "",
    aliases: []
  },
  {
    code: "usd_broad",
    zh: "广义美元指数",
    en: "Broad U.S. dollar index",
    category: "海外市场",
    storage_unit: "raw",
    display_unit: "number",
    importance: "重要",
    rise: "通常意味着美元走强、外部金融条件偏紧。",
    fall: "通常意味着美元走弱、外部金融条件边际放松。",
    usage: "观察美元周期。",
    note: "",
    aliases: []
  },
  {
    code: "usd_cny",
    zh: "美元兑人民币即期",
    en: "USD/CNY spot",
    category: "汇率",
    storage_unit: "raw",
    display_unit: "number",
    importance: "核心",
    rise: "通常意味着人民币贬值压力增大。",
    fall: "通常意味着人民币升值或贬值压力缓和。",
    usage: "观察汇率与外部约束。",
    note: "",
    aliases: []
  },
  {
    code: "gold",
    zh: "黄金价格",
    en: "Gold price",
    category: "商品与避险",
    storage_unit: "raw",
    display_unit: "number",
    importance: "观察",
    rise: "通常意味着避险需求、通胀对冲需求或美元信用担忧上升。",
    fall: "通常意味着避险需求回落。",
    usage: "辅助观察避险情绪。",
    note: "",
    aliases: []
  },
  {
    code: "wti",
    zh: "WTI原油价格",
    en: "WTI crude oil price",
    category: "商品",
    storage_unit: "raw",
    display_unit: "number",
    importance: "观察",
    rise: "通常意味着能源价格与通胀压力上升。",
    fall: "通常意味着能源价格与通胀压力回落。",
    usage: "辅助观察全球通胀压力。",
    note: "",
    aliases: []
  },
  {
    code: "brent",
    zh: "布伦特原油价格",
    en: "Brent crude oil price",
    category: "商品",
    storage_unit: "raw",
    display_unit: "number",
    importance: "观察",
    rise: "通常意味着能源价格与通胀压力上升。",
    fall: "通常意味着能源价格与通胀压力回落。",
    usage: "辅助观察全球通胀压力。",
    note: "",
    aliases: []
  },
  {
    code: "copper",
    zh: "铜价",
    en: "Copper price",
    category: "商品",
    storage_unit: "raw",
    display_unit: "number",
    importance: "观察",
    rise: "通常意味着工业活动和全球增长预期改善。",
    fall: "通常意味着工业活动和全球增长预期走弱。",
    usage: "辅助观察经济景气。",
    note: "",
    aliases: []
  },
  {
    code: "vix",
    zh: "VIX波动率指数",
    en: "VIX volatility index",
    category: "海外市场",
    storage_unit: "raw",
    display_unit: "number",
    importance: "重要",
    rise: "通常意味着风险厌恶上升。",
    fall: "通常意味着风险偏好改善。",
    usage: "观察全球风险情绪。",
    note: "",
    aliases: []
  },
  {
    code: "spx",
    zh: "标普500指数",
    en: "S&P 500 Index",
    category: "海外市场",
    storage_unit: "raw",
    display_unit: "number",
    importance: "重要",
    rise: "通常意味着美股风险偏好与盈利预期改善。",
    fall: "通常意味着美股风险偏好转弱。",
    usage: "观察全球风险资产表现。",
    note: "",
    aliases: []
  },
  {
    code: "nasdaq_100",
    zh: "纳斯达克100指数",
    en: "Nasdaq-100 Index",
    category: "海外市场",
    storage_unit: "raw",
    display_unit: "number",
    importance: "观察",
    rise: "通常意味着成长风格风险偏好改善。",
    fall: "通常意味着成长风格承压。",
    usage: "观察成长资产表现。",
    note: "",
    aliases: []
  },
  {
    code: "slope_gov_10y_1y_bp",
    zh: "国债10年-1年期限利差",
    en: "CGB 10Y-1Y curve slope",
    category: "曲线斜率",
    storage_unit: "bp",
    display_unit: "bp",
    importance: "核心",
    rise: "曲线变陡，常对应增长/通胀预期改善或宽货币向中长端传导。",
    fall: "曲线走平或倒挂，常对应增长预期走弱、短端偏紧或长端避险买盘增强。",
    usage: "观察国债曲线形态。",
    note: "",
    aliases: ["gov_slope_10_1"]
  },
  {
    code: "slope_gov_10y_3y_bp",
    zh: "国债10年-3年期限利差",
    en: "CGB 10Y-3Y curve slope",
    category: "曲线斜率",
    storage_unit: "bp",
    display_unit: "bp",
    importance: "重要",
    rise: "曲线变陡。",
    fall: "曲线走平。",
    usage: "观察中长端曲线斜率。",
    note: "",
    aliases: ["gov_slope_10_3"]
  },
  {
    code: "slope_gov_30y_10y_bp",
    zh: "国债30年-10年期限利差",
    en: "CGB 30Y-10Y curve slope",
    category: "曲线斜率",
    storage_unit: "bp",
    display_unit: "bp",
    importance: "重要",
    rise: "超长端相对长端更弱或供给压力更大。",
    fall: "超长端更强、久期偏好提升。",
    usage: "观察超长端久期偏好。",
    note: "",
    aliases: ["gov_slope_30_10"]
  },
  {
    code: "slope_cdb_10y_3y_bp",
    zh: "国开债10年-3年期限利差",
    en: "CDB 10Y-3Y curve slope",
    category: "曲线斜率",
    storage_unit: "bp",
    display_unit: "bp",
    importance: "观察",
    rise: "国开曲线变陡。",
    fall: "国开曲线走平。",
    usage: "观察国开曲线形态。",
    note: "",
    aliases: ["cdb_slope_10_3"]
  },
  {
    code: "spread_cdb_gov_3y_bp",
    zh: "国开-国债3年利差",
    en: "CDB-CGB 3Y spread",
    category: "相对价值",
    storage_unit: "bp",
    display_unit: "bp",
    importance: "重要",
    rise: "通常意味着国开债相对国债走弱、利差走阔。",
    fall: "通常意味着国开债相对国债走强、利差收窄。",
    usage: "观察利率债相对价值。",
    note: "",
    aliases: ["spread_cdb_gov_3y"]
  },
  {
    code: "spread_cdb_gov_5y_bp",
    zh: "国开-国债5年利差",
    en: "CDB-CGB 5Y spread",
    category: "相对价值",
    storage_unit: "bp",
    display_unit: "bp",
    importance: "重要",
    rise: "通常意味着国开债相对国债走弱。",
    fall: "通常意味着国开债相对国债走强。",
    usage: "观察利率债相对价值。",
    note: "",
    aliases: ["spread_cdb_gov_5y"]
  },
  {
    code: "spread_cdb_gov_10y_bp",
    zh: "国开-国债10年利差",
    en: "CDB-CGB 10Y spread",
    category: "相对价值",
    storage_unit: "bp",
    display_unit: "bp",
    importance: "核心",
    rise: "通常意味着国开债相对国债走弱、政策性金融债风险补偿上升。",
    fall: "通常意味着国开债相对国债走强。",
    usage: "核心利率债相对价值指标。",
    note: "",
    aliases: ["spread_cdb_gov_10y"]
  },
  {
    code: "spread_local_gov_gov_5y_bp",
    zh: "地方债-国债5年利差",
    en: "Local government bond-CGB 5Y spread",
    category: "相对价值",
    storage_unit: "bp",
    display_unit: "bp",
    importance: "观察",
    rise: "通常意味着地方债相对国债走弱。",
    fall: "通常意味着地方债相对国债走强。",
    usage: "观察地方债相对价值。",
    note: "",
    aliases: ["spread_local_gov_gov_5y"]
  },
  {
    code: "spread_local_gov_gov_10y_bp",
    zh: "地方债-国债10年利差",
    en: "Local government bond-CGB 10Y spread",
    category: "相对价值",
    storage_unit: "bp",
    display_unit: "bp",
    importance: "观察",
    rise: "通常意味着地方债相对国债走弱。",
    fall: "通常意味着地方债相对国债走强。",
    usage: "观察地方债相对价值。",
    note: "",
    aliases: ["spread_local_gov_gov_10y"]
  },
  {
    code: "spread_aaa_credit_gov_1y_bp",
    zh: "AAA信用-国债1年利差",
    en: "AAA credit-CGB 1Y spread",
    category: "信用利差",
    storage_unit: "bp",
    display_unit: "bp",
    importance: "重要",
    rise: "通常意味着高等级信用相对国债走弱、信用溢价上升。",
    fall: "通常意味着高等级信用相对国债走强、信用溢价回落。",
    usage: "观察高等级信用短端利差。",
    note: "",
    aliases: ["spread_aaa_credit_gov_1y"]
  },
  {
    code: "spread_aaa_credit_gov_3y_bp",
    zh: "AAA信用-国债3年利差",
    en: "AAA credit-CGB 3Y spread",
    category: "信用利差",
    storage_unit: "bp",
    display_unit: "bp",
    importance: "重要",
    rise: "通常意味着高等级信用中端利差走阔。",
    fall: "通常意味着高等级信用中端利差收窄。",
    usage: "观察高等级信用中端利差。",
    note: "",
    aliases: ["spread_aaa_credit_gov_3y"]
  },
  {
    code: "spread_aaa_credit_gov_5y_bp",
    zh: "AAA信用-国债5年利差",
    en: "AAA credit-CGB 5Y spread",
    category: "信用利差",
    storage_unit: "bp",
    display_unit: "bp",
    importance: "核心",
    rise: "通常意味着高等级信用相对利率债走弱、风险补偿上升。",
    fall: "通常意味着高等级信用相对利率债走强。",
    usage: "核心信用利差指标。",
    note: "",
    aliases: ["spread_aaa_credit_gov_5y"]
  },
  {
    code: "spread_aa_plus_credit_aaa_credit_1y_bp",
    zh: "AA+信用-AAA信用1年利差",
    en: "AA+ credit-AAA credit 1Y spread",
    category: "信用利差",
    storage_unit: "bp",
    display_unit: "bp",
    importance: "重要",
    rise: "通常意味着下沉信用风险补偿上升。",
    fall: "通常意味着市场愿意下沉、风险偏好改善。",
    usage: "观察信用下沉空间。",
    note: "",
    aliases: ["spread_aa_plus_vs_aaa_credit_1y"]
  },
  {
    code: "spread_aaa_plus_mtn_gov_1y_bp",
    zh: "AAA+中票-国债1年利差",
    en: "AAA+ MTN-CGB 1Y spread",
    category: "信用利差",
    storage_unit: "bp",
    display_unit: "bp",
    importance: "观察",
    rise: "通常意味着高等级中票相对国债走弱。",
    fall: "通常意味着高等级中票相对国债走强。",
    usage: "观察中票相对价值。",
    note: "",
    aliases: ["spread_aaa_plus_mtn_gov_1y"]
  },
  {
    code: "spread_aaa_mtn_aaa_plus_mtn_1y_bp",
    zh: "AAA中票-AAA+中票1年利差",
    en: "AAA MTN-AAA+ MTN 1Y spread",
    category: "信用利差",
    storage_unit: "bp",
    display_unit: "bp",
    importance: "观察",
    rise: "通常意味着中票内部等级补偿上升。",
    fall: "通常意味着中票内部等级补偿回落。",
    usage: "观察中票内部结构。",
    note: "",
    aliases: ["spread_aaa_mtn_vs_aaa_plus_mtn_1y"]
  },
  {
    code: "spread_aaa_credit_ncd_1y_bp",
    zh: "AAA信用-AAA存单1年利差",
    en: "AAA credit-AAA NCD 1Y spread",
    category: "相对价值",
    storage_unit: "bp",
    display_unit: "bp",
    importance: "观察",
    rise: "通常意味着信用债相对存单走弱。",
    fall: "通常意味着信用债相对存单走强。",
    usage: "观察资产端与负债端相对性价比。",
    note: "",
    aliases: ["spread_aaa_credit_ncd_1y"]
  },
  {
    code: "spread_aaa_bank_bond_aaa_credit_1y_bp",
    zh: "AAA银行债-AAA信用1年利差",
    en: "AAA bank bond-AAA credit 1Y spread",
    category: "相对价值",
    storage_unit: "bp",
    display_unit: "bp",
    importance: "观察",
    rise: "通常意味着银行债相对高等级信用走弱。",
    fall: "通常意味着银行债相对高等级信用走强。",
    usage: "观察银行债相对价值。",
    note: "",
    aliases: ["spread_aaa_bank_vs_aaa_credit_1y", "spread_bank_bond_vs_high_grade_credit_1y"]
  },
  {
    code: "spread_aaa_bank_bond_aaa_credit_3y_bp",
    zh: "AAA银行债-AAA信用3年利差",
    en: "AAA bank bond-AAA credit 3Y spread",
    category: "相对价值",
    storage_unit: "bp",
    display_unit: "bp",
    importance: "观察",
    rise: "通常意味着银行债相对高等级信用走弱。",
    fall: "通常意味着银行债相对高等级信用走强。",
    usage: "观察银行债相对价值。",
    note: "",
    aliases: ["spread_aaa_bank_vs_aaa_credit_3y", "spread_bank_bond_vs_high_grade_credit_3y"]
  },
  {
    code: "spread_aaa_bank_bond_aaa_credit_5y_bp",
    zh: "AAA银行债-AAA信用5年利差",
    en: "AAA bank bond-AAA credit 5Y spread",
    category: "相对价值",
    storage_unit: "bp",
    display_unit: "bp",
    importance: "观察",
    rise: "通常意味着银行债相对高等级信用走弱。",
    fall: "通常意味着银行债相对高等级信用走强。",
    usage: "观察银行债相对价值。",
    note: "",
    aliases: ["spread_aaa_bank_vs_aaa_credit_5y", "spread_bank_bond_vs_high_grade_credit_5y"]
  },
  {
    code: "spread_aaa_lgfv_aaa_credit_1y_bp",
    zh: "AAA城投-AAA信用1年利差",
    en: "AAA LGFV-AAA credit 1Y spread",
    category: "信用利差",
    storage_unit: "bp",
    display_unit: "bp",
    importance: "重要",
    rise: "通常意味着城投相对产业信用走弱或融资约束上升。",
    fall: "通常意味着城投相对产业信用走强。",
    usage: "观察城投风险补偿。",
    note: "",
    aliases: ["spread_aaa_lgfv_vs_aaa_credit_1y", "spread_lgfv_vs_high_grade_credit_1y"]
  },
  {
    code: "spread_dr007_omo_7d_bp",
    zh: "DR007-7天逆回购利差",
    en: "DR007-7D reverse repo spread",
    category: "政策—市场联动",
    storage_unit: "bp",
    display_unit: "bp",
    importance: "核心",
    rise: "通常意味着市场资金价格高于政策利率更多，资金面偏紧。",
    fall: "通常意味着市场资金价格更接近或低于政策利率，资金面偏松。",
    usage: "观察政策利率向市场利率的传导。",
    note: "",
    aliases: ["spread_dr007_omo_7d"]
  },
  {
    code: "spread_ncd_mlf_1y_bp",
    zh: "AAA存单-1年MLF利差",
    en: "AAA NCD-1Y MLF spread",
    category: "政策—市场联动",
    storage_unit: "bp",
    display_unit: "bp",
    importance: "核心",
    rise: "通常意味着银行负债成本相对政策利率抬升。",
    fall: "通常意味着银行负债成本相对政策利率回落。",
    usage: "观察银行负债端压力。",
    note: "",
    aliases: ["spread_ncd_1y_mlf_1y", "spread_ncd_mlf_1y"]
  },
  {
    code: "spread_gov_mlf_1y_bp",
    zh: "1年国债-1年MLF利差",
    en: "1Y CGB-1Y MLF spread",
    category: "政策—市场联动",
    storage_unit: "bp",
    display_unit: "bp",
    importance: "观察",
    rise: "通常意味着市场定价高于政策锚。",
    fall: "通常意味着市场定价低于政策锚。",
    usage: "观察短端国债与政策利率关系。",
    note: "",
    aliases: ["spread_gov_1y_mlf_1y"]
  },
  {
    code: "spread_lpr_mlf_1y_bp",
    zh: "1年LPR-1年MLF利差",
    en: "1Y LPR-1Y MLF spread",
    category: "政策—市场联动",
    storage_unit: "bp",
    display_unit: "bp",
    importance: "重要",
    rise: "通常意味着贷款报价对政策利率加点更高。",
    fall: "通常意味着贷款报价加点收窄。",
    usage: "观察贷款定价传导。",
    note: "",
    aliases: ["spread_lpr_1y_mlf_1y"]
  },
  {
    code: "spread_lpr_gov_5y_bp",
    zh: "5年LPR-5年国债利差",
    en: "5Y LPR-5Y CGB spread",
    category: "政策—市场联动",
    storage_unit: "bp",
    display_unit: "bp",
    importance: "重要",
    rise: "通常意味着按揭/长期贷款定价相对债券利率更高。",
    fall: "通常意味着按揭/长期贷款定价相对债券利率回落。",
    usage: "观察中长期融资环境。",
    note: "",
    aliases: ["spread_lpr_5y_gov_5y", "spread_lpr5y_gov5y"]
  },
  {
    code: "spread_lpr5y_ncd1y_bp",
    zh: "5年LPR-1年AAA存单利差",
    en: "5Y LPR-1Y AAA NCD spread",
    category: "政策—市场联动",
    storage_unit: "bp",
    display_unit: "bp",
    importance: "观察",
    rise: "通常意味着贷款端相对银行负债端利差更厚。",
    fall: "通常意味着贷款端相对银行负债端利差压缩。",
    usage: "观察银行息差环境的粗略代理。",
    note: "",
    aliases: ["spread_lpr_5y_ncd_1y"]
  },
  {
    code: "spread_gov_ust_10y_bp",
    zh: "中美国债10年利差",
    en: "China-U.S. 10Y government bond spread",
    category: "海外约束",
    storage_unit: "bp",
    display_unit: "bp",
    importance: "核心",
    rise: "通常意味着中美长端利差扩大，人民币与跨境资金压力趋缓。",
    fall: "通常意味着中美长端利差收窄，外部约束增强。",
    usage: "观察汇率与跨境资金压力。",
    note: "",
    aliases: ["cn_us_10y_spread"]
  },
  {
    code: "spread_gov_ust_2y_bp",
    zh: "中美国债2年利差",
    en: "China-U.S. 2Y government bond spread",
    category: "海外约束",
    storage_unit: "bp",
    display_unit: "bp",
    importance: "重要",
    rise: "通常意味着中美短端利差扩大。",
    fall: "通常意味着中美短端利差收窄。",
    usage: "观察短端政策利率相对位置。",
    note: "",
    aliases: ["cn_us_2y_spread"]
  },
  {
    code: "usd_broad_ma20",
    zh: "广义美元指数20日均线",
    en: "Broad U.S. dollar index 20-day moving average",
    category: "海外市场",
    storage_unit: "raw",
    display_unit: "number",
    importance: "观察",
    rise: "表示对应基础序列的中期中枢上移。",
    fall: "表示对应基础序列的中期中枢下移。",
    usage: "用于平滑短期噪音，观察趋势方向与拐点。",
    note: "派生指标；基于基础序列滚动计算。",
    aliases: []
  },
  {
    code: "usd_cny_ma20",
    zh: "美元兑人民币即期20日均线",
    en: "USD/CNY spot 20-day moving average",
    category: "汇率",
    storage_unit: "raw",
    display_unit: "number",
    importance: "观察",
    rise: "表示对应基础序列的中期中枢上移。",
    fall: "表示对应基础序列的中期中枢下移。",
    usage: "用于平滑短期噪音，观察趋势方向与拐点。",
    note: "派生指标；基于基础序列滚动计算。",
    aliases: []
  },
  {
    code: "gold_ma20",
    zh: "黄金价格20日均线",
    en: "Gold price 20-day moving average",
    category: "商品与避险",
    storage_unit: "raw",
    display_unit: "number",
    importance: "观察",
    rise: "表示对应基础序列的中期中枢上移。",
    fall: "表示对应基础序列的中期中枢下移。",
    usage: "用于平滑短期噪音，观察趋势方向与拐点。",
    note: "派生指标；基于基础序列滚动计算。",
    aliases: []
  },
  {
    code: "ust_10y_prank250",
    zh: "10年期美债收益率250日历史分位",
    en: "10Y U.S. Treasury yield 250-day percentile rank",
    category: "海外利率",
    storage_unit: "ratio",
    display_unit: "percent",
    importance: "观察",
    rise: "表示当前值在近250日样本中处于更高位置。",
    fall: "表示当前值在近250日样本中处于更低位置。",
    usage: "用于判断当前水平在历史滚动窗口中的相对高低。",
    note: "派生指标；percentile rank，不是涨跌幅。",
    aliases: ["ust_10y_pct250"]
  },
  {
    code: "usd_cny_prank250",
    zh: "美元兑人民币即期250日历史分位",
    en: "USD/CNY spot 250-day percentile rank",
    category: "汇率",
    storage_unit: "ratio",
    display_unit: "percent",
    importance: "观察",
    rise: "表示当前值在近250日样本中处于更高位置。",
    fall: "表示当前值在近250日样本中处于更低位置。",
    usage: "用于判断当前水平在历史滚动窗口中的相对高低。",
    note: "派生指标；percentile rank，不是涨跌幅。",
    aliases: ["usd_cny_pct250"]
  },
  {
    code: "gov_10y_ma20",
    zh: "10年期国债到期收益率20日均线",
    en: "10Y China Government Bond yield 20-day moving average",
    category: "利率水平",
    storage_unit: "decimal",
    display_unit: "percent",
    importance: "观察",
    rise: "表示对应基础序列的中期中枢上移。",
    fall: "表示对应基础序列的中期中枢下移。",
    usage: "用于平滑短期噪音，观察趋势方向与拐点。",
    note: "派生指标；基于基础序列滚动计算。",
    aliases: []
  },
  {
    code: "gov_10y_ma60",
    zh: "10年期国债到期收益率60日均线",
    en: "10Y China Government Bond yield 60-day moving average",
    category: "利率水平",
    storage_unit: "decimal",
    display_unit: "percent",
    importance: "观察",
    rise: "表示对应基础序列的中期中枢上移。",
    fall: "表示对应基础序列的中期中枢下移。",
    usage: "用于平滑短期噪音，观察趋势方向与拐点。",
    note: "派生指标；基于基础序列滚动计算。",
    aliases: []
  },
  {
    code: "gov_10y_ma120",
    zh: "10年期国债到期收益率120日均线",
    en: "10Y China Government Bond yield 120-day moving average",
    category: "利率水平",
    storage_unit: "decimal",
    display_unit: "percent",
    importance: "观察",
    rise: "表示对应基础序列的中期中枢上移。",
    fall: "表示对应基础序列的中期中枢下移。",
    usage: "用于平滑短期噪音，观察趋势方向与拐点。",
    note: "派生指标；基于基础序列滚动计算。",
    aliases: []
  },
  {
    code: "gov_10y_prank250",
    zh: "10年期国债到期收益率250日历史分位",
    en: "10Y China Government Bond yield 250-day percentile rank",
    category: "利率水平",
    storage_unit: "ratio",
    display_unit: "percent",
    importance: "观察",
    rise: "表示当前值在近250日样本中处于更高位置。",
    fall: "表示当前值在近250日样本中处于更低位置。",
    usage: "用于判断当前水平在历史滚动窗口中的相对高低。",
    note: "派生指标；percentile rank，不是涨跌幅。",
    aliases: ["gov_10y_pct250"]
  },
  {
    code: "spread_cdb_gov_10y_bp_ma20",
    zh: "国开-国债10年利差20日均线",
    en: "CDB-CGB 10Y spread 20-day moving average",
    category: "相对价值",
    storage_unit: "bp",
    display_unit: "bp",
    importance: "观察",
    rise: "表示对应基础序列的中期中枢上移。",
    fall: "表示对应基础序列的中期中枢下移。",
    usage: "用于平滑短期噪音，观察趋势方向与拐点。",
    note: "派生指标；基于基础序列滚动计算。",
    aliases: ["spread_cdb_gov_10y_ma20"]
  },
  {
    code: "spread_cdb_gov_10y_bp_prank250",
    zh: "国开-国债10年利差250日历史分位",
    en: "CDB-CGB 10Y spread 250-day percentile rank",
    category: "相对价值",
    storage_unit: "ratio",
    display_unit: "percent",
    importance: "观察",
    rise: "表示当前值在近250日样本中处于更高位置。",
    fall: "表示当前值在近250日样本中处于更低位置。",
    usage: "用于判断当前水平在历史滚动窗口中的相对高低。",
    note: "派生指标；percentile rank，不是涨跌幅。",
    aliases: ["spread_cdb_gov_10y_pct250"]
  },
  {
    code: "spread_aaa_credit_gov_5y_bp_ma20",
    zh: "AAA信用-国债5年利差20日均线",
    en: "AAA credit-CGB 5Y spread 20-day moving average",
    category: "信用利差",
    storage_unit: "bp",
    display_unit: "bp",
    importance: "观察",
    rise: "表示对应基础序列的中期中枢上移。",
    fall: "表示对应基础序列的中期中枢下移。",
    usage: "用于平滑短期噪音，观察趋势方向与拐点。",
    note: "派生指标；基于基础序列滚动计算。",
    aliases: ["spread_aaa_credit_gov_5y_ma20"]
  },
  {
    code: "spread_aaa_credit_gov_5y_bp_prank250",
    zh: "AAA信用-国债5年利差250日历史分位",
    en: "AAA credit-CGB 5Y spread 250-day percentile rank",
    category: "信用利差",
    storage_unit: "ratio",
    display_unit: "percent",
    importance: "观察",
    rise: "表示当前值在近250日样本中处于更高位置。",
    fall: "表示当前值在近250日样本中处于更低位置。",
    usage: "用于判断当前水平在历史滚动窗口中的相对高低。",
    note: "派生指标；percentile rank，不是涨跌幅。",
    aliases: ["spread_aaa_credit_gov_5y_pct250"]
  },
  {
    code: "spread_aa_plus_credit_aaa_credit_1y_bp_ma20",
    zh: "AA+信用-AAA信用1年利差20日均线",
    en: "AA+ credit-AAA credit 1Y spread 20-day moving average",
    category: "信用利差",
    storage_unit: "bp",
    display_unit: "bp",
    importance: "观察",
    rise: "表示对应基础序列的中期中枢上移。",
    fall: "表示对应基础序列的中期中枢下移。",
    usage: "用于平滑短期噪音，观察趋势方向与拐点。",
    note: "派生指标；基于基础序列滚动计算。",
    aliases: ["spread_aa_plus_vs_aaa_credit_1y_ma20"]
  },
  {
    code: "spread_aa_plus_credit_aaa_credit_1y_bp_prank250",
    zh: "AA+信用-AAA信用1年利差250日历史分位",
    en: "AA+ credit-AAA credit 1Y spread 250-day percentile rank",
    category: "信用利差",
    storage_unit: "ratio",
    display_unit: "percent",
    importance: "观察",
    rise: "表示当前值在近250日样本中处于更高位置。",
    fall: "表示当前值在近250日样本中处于更低位置。",
    usage: "用于判断当前水平在历史滚动窗口中的相对高低。",
    note: "派生指标；percentile rank，不是涨跌幅。",
    aliases: ["spread_aa_plus_vs_aaa_credit_1y_pct250"]
  },
  {
    code: "aaa_ncd_1y_ma20",
    zh: "1年期AAA同业存单到期收益率20日均线",
    en: "1Y AAA negotiable certificate of deposit yield 20-day moving average",
    category: "资金与存单",
    storage_unit: "decimal",
    display_unit: "percent",
    importance: "观察",
    rise: "表示对应基础序列的中期中枢上移。",
    fall: "表示对应基础序列的中期中枢下移。",
    usage: "用于平滑短期噪音，观察趋势方向与拐点。",
    note: "派生指标；基于基础序列滚动计算。",
    aliases: []
  },
  {
    code: "aaa_ncd_1y_prank250",
    zh: "1年期AAA同业存单到期收益率250日历史分位",
    en: "1Y AAA negotiable certificate of deposit yield 250-day percentile rank",
    category: "资金与存单",
    storage_unit: "ratio",
    display_unit: "percent",
    importance: "观察",
    rise: "表示当前值在近250日样本中处于更高位置。",
    fall: "表示当前值在近250日样本中处于更低位置。",
    usage: "用于判断当前水平在历史滚动窗口中的相对高低。",
    note: "派生指标；percentile rank，不是涨跌幅。",
    aliases: ["aaa_ncd_1y_pct250"]
  }
];